fields:
  - name: Version
    value: 2
  - name: AccountID
    value: 627286350134
  - name: InterfaceID
    cardinality: 100
  - name: SrcAddr
    cardinality: 1000
  - name: DstAddr
    cardinality: 10
  - name: SrcPort
    range:
      min: 0
      max: 65535
  - name: DstPort
    range:
      min: 0
      max: 65535
    cardinality: 10
  - name: Protocol
    range:
      min: 1
      max: 256
  - name: Packets
    range:
      min: 1
      max: 1048576
  - name: Bytes
    range:
      min: 1
      max: 15728640
  - name: StartOffset
    range:
      min: 1
      max: 60
  - name: Action
    enum: ["ACCEPT", "REJECT"]
  - name: LogStatus
    enum: ["OK", "SKIPDATA"]