{{- $period := generate "metricset.period" }}
{{- $index := generate "index" }}
{{- $timestamp := generate "timestamp" }}
{{- $fulltimestamp := $timestamp.Format "2006-01-02T15:04:05.999999Z07:00" }}
{{- $resttime := split ":" $fulltimestamp }}
{{- $timedate := generate "timedate" }}
{{- $hour := generate "hour" }}
{{- $minute := generate "minute" }}
{{- $second := generate "second" }}
{{- $agentId := generate "agent.id" }}
{{- $agentVersion := generate "agent.version" }}
{{- $agentName := generate "agent.name" }}
{{- $agentEphemeralid := generate "agent.ephemeral_id" }}
{{- $uId := uuidv4 }}
{{- $docId := uuidv4 }}
{{- $rangeofid := generate "rangeofid" }}
{ "create": { } }
{ "@timestamp": "{{$timedate}}T{{$hour}}:{{$minute}}:{{$second}}", "kubernetes": { "node":{ "uid": "{{ $uId }}" , "hostname":"{{ $agentName }}.c.elastic-obs-integrations-dev.internal", "name":"{{ $agentName }}-{{ $rangeofid }}", "labels":{ "cloud_google_com/machine-family":"e2", "cloud_google_com/gke-nodepool":"kubernetes-scale-nl", "kubernetes_io/hostname":"{{ $agentName }}-{{ $uId }}", "cloud_google_com/gke-os-distribution":"cos", "topology_kubernetes_io/zone":"europe-west1-d", "topology_gke_io/zone":"europe-west1-d", "topology_kubernetes_io/region":"europe-west1", "kubernetes_io/arch":"amd64", "cloud_google_com/gke-cpu-scaling-level":"4", "env":"kubernetes-scale", "failure-domain_beta_kubernetes_io/region":"europe-west1", "cloud_google_com/gke-max-pods-per-node":"110", "cloud_google_com/gke-container-runtime":"containerd", "beta_kubernetes_io/instance-type":"e2-standard-4", "failure-domain_beta_kubernetes_io/zone":"europe-west1-d", "node_kubernetes_io/instance-type":"e2-standard-4", "beta_kubernetes_io/os":"linux", "cloud_google_com/gke-boot-disk":"pd-balanced", "kubernetes_io/os":"linux", "cloud_google_com/private-node":"false", "cloud_google_com/gke-logging-variant":"DEFAULT", "beta_kubernetes_io/arch":"amd64" } }}, "cloud": { "provider": "gcp", "availability_zone": "europe-west1-d", "instance":{ "name": "{{ $agentName }}" , "id": "{{ $agentId }}" }, "machine":{ "type":"e2-standard-4" }, "service":{ "name":"GCE" }, "project":{ "id":"elastic-obs-integrations-dev" }, "account":{ "id":"elastic-obs-integrations-dev" } }, "orchestrator":{ "cluster":{ "name":"kubernetes-scale" } }, "service":{ "address": "https://{{ $agentName }}-{{ $rangeofid }}:10250/stats/summary", "type":"kubernetes" }, "data_stream":{ "namespace":"default", "type":"metrics", "dataset":"kubernetes.node" }, "ecs": { "version": "8.2.0" }, "agent": { "id": "{{ $agentId}}", "name": "{{ $agentName }}" , "type": "metricbeat", "version": "{{ $agentVersion }}", "ephemeral_id": "{{ $agentEphemeralid }}" }, "elastic_agent": { "id": "{{ $agentId }}" , "version": "{{ $agentVersion }}", "snapshot": {{ generate "agent.snapshot" }} }, "metricset":{ "period": "{{ $period }}" , "name":"node" }, "event":{ "duration": "{{generate "event.duration"}}", "agent_id_status": "verified", "ingested": "{{$timedate}}T{{$hour}}:{{$minute}}:{{$second}}", "module":"kubernetes", "dataset":"kubernetes.node" }, "host":{ "hostname":"{{ $agentName }}", "os":{ "kernel":"5.10.161+", "codename":"focal", "name":"Ubuntu", "type":"linux", "family":"debian", "version":"20.04.5 LTS (Focal Fossa)", "platform":"ubuntu" }, "containerized":false, "ip":[ "10.10.0.186", "fe80::5d:14ff:fec1:2d3a" ], "name": "{{ $agentName }}", "id": "{{ $uId }}", "mac":[ "02-42-1F-C0-F0-D2", "FE-F1-90-50-28-AD" ], "architecture":"x86_64" } }