fields:
  - name: cloud.availabilit_zone
    value: "europe-west1-d"  
  - name: agent.id
    value: "12f376ef-5186-4e8b-a175-70f1140a8f30"
  - name: agent.name
    value: "kubernetes-scale-123456"
  - name: agent.ephemeral_id  
    value: "f94220b0-2ca6-4809-8656-eb478a66c541"
  - name: agent.version
    value: "8.7.0"
  - name: agent.snasphost
    value: false
  - name: metricset.period
    value: 10000
  - name: event.duration
    range:
      min: 1
      max: 4000000
  - name: faults
    range:
      min: 0
      max: 500000
  - name: kubernetes.container.rootfs.inodes.used
    range:
      min: 1
      max: 100000
  - name: Bytes
    range:
      min: 1
      max: 3000000
  - name: rangeofid
    range:
      min: 0
      max: 10000
  - name: PercentageMemory
    range:
      min: 0.0
      max: 1.0
  - name: PercentageCPU
    range:
      min: 0.0
      max: 1.0
  - name: usage.*
    object_keys:
      - nanoseconds
      - nanocores
  - name: usage.nanoseconds
    range:
      min: 100000
      max: 9000000000
    cardinality: 10000
  - name: usage.nanocores
    range:
      min: 100000
      max: 9000000
    cardinality: 10000
  - name: container.name
    enum: ["web", "default-http-backend", "dnsmasq", "csi-driver", "web", "web", "web", "prometheus", "konnectivity-agent", "sidecar", "kubedns", "metrics-server-nanny", "web", "web", "fluentbit", "autoscaler", "gke-metrics-agent", "elastic-agent", "web", "kube-state-metrics", "metrics-server", "fluentbit", "elastic-agent", "web", "prometheus-to-sd-exporter"]
  - name: timedate
    # Add more dates below in case you want your data to be spread.Those are fixed because this is required in the nightly tests of Rally
    enum: ["2023-05-15" , "2023-05-16"]
  - name: timehour
    # Repeat or remove hours below to make data appear in specific hours. Below default enumaeration makes sure that data are spread throughout the 24 hours
    enum: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" ]  