- name: cloud.region
  enum: ["us-east-1", "us-east-2", "us-west-1", "us-west-2", "ap-south-1", "ap-northeast-3", "ap-northeast-2", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ca-central-1", "eu-central-1", "eu-west-1", "eu-west-2", "eu-west-3", "eu-north-1", "sa-east-1", "af-south-1", "ap-east-1", "ap-south-2", "ap-southeast-3", "eu-south-2", "eu-central-2", "me-south-1", "me-central-1"]
  cardinality:
    numerator: 1
    denominator: 25
- name: cloud.account.id
  value: 123456789
- name: cloud.account.name
  value: sample-account
- name: aws.billing.currency
  value: "USD"
- name: aws.billing.ServiceName
  enum: ["AmazonEKS"]
- name: agent.id
  value: "12f376ef-5186-4e8b-a175-70f1140a8f30"
- name: agent.name
  value: "host.local"
- name: metrics.period
  value: 60
- name: event.duration
  range:
    min: 1
    max: 1000
- name: aws.billing.EstimatedCharges
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
- name: aws.billing.AmortizedCost.amount
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
- name: aws.billing.BlendedCost.amount
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
- name: aws.billing.NormalizedUsageAmount.amount
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
- name: aws.billing.UnblendedCost.amount
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
- name: aws.billing.UsageQuantity.amount
  cardinality:
    numerator: 1
    denominator: 25
  fuzziness:
    numerator: 1
    denominator: 5
