- name: Region
  enum: ["us-east-1", "us-east-2", "us-west-1", "us-west-2", "ap-south-1", "ap-northeast-3", "ap-northeast-2", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1", "ca-central-1", "eu-central-1", "eu-west-1", "eu-west-2", "eu-west-3", "eu-north-1", "sa-east-1", "af-south-1", "ap-east-1", "ap-south-2", "ap-southeast-3", "eu-south-2", "eu-central-2", "me-south-1", "me-central-1"]
  cardinality:
    numerator: 1
    denominator: 25
- name: Visible
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: Deleted
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: NotVisible
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: Delayed
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: Received
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: Sent
  range:
    min: 0
    max: 1000
  fuzziness:
    numerator: 1
    denominator: 20
- name: EmptyReceives
  range:
    min: 0
    max: 10
  fuzziness:
    numerator: 1
    denominator: 10
- name: SentMessageSize
  range:
    min: 1024
    max: 262144
  fuzziness:
    numerator: 1
    denominator: 2
- name: OldestMessageAge
  range:
    min: 1
    max: 7200
  fuzziness:
    numerator: 1
    denominator: 20
- name: QueueName
  cardinality:
    numerator: 1
    denominator: 200
- name: EventDuration
  range:
    min: 1
    max: 1000
- name: TagsCreatedBy
  cardinality:
    numerator: 1
    denominator: 200
